
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://*********/BiliBli
    username: ****
    password: ****
  thymeleaf:
    cache: true

##将mapper级别热日志最低级别调整为debug
#logging:
#  level:
#    com.jinxiu123.bilibili.mapper: debug
server:
  port: **
